/** IPC CONSTANTS */
const IPC_GET_AUTH_TOKENS = 'IPC_GET_AUTH_TOKENS'
const IPC_ACTIVATE_AUTHORIZATION = 'IPC_ACTIVATE_AUTHORIZATION'
const IPC_POST_AUTH_TOKENS = 'IPC_POST_AUTH_TOKENS'

/** URL */
const LOCALHOST_URL = 'http://localhost:8080/peacock-api/api'
const HTTP_GET = 'GET'
const HTTP_PUT = 'PUT'
const HTTP_POST = 'POST'
const HTTP_DELETE = 'DELETE'

/** MISC. */
const REQ_TIMEOUT = 1000

module.exports = {
  IPC_GET_AUTH_TOKENS,
  IPC_ACTIVATE_AUTHORIZATION,
  IPC_POST_AUTH_TOKENS,

  LOCALHOST_URL,
  HTTP_GET,
  HTTP_PUT,
  HTTP_POST,
  HTTP_DELETE,

  REQ_TIMEOUT
}